api.token = Token 469a47f54c1e3b23fde76accd7a2c79171127a8c

idFetcher.url = http://dronesim.facets-labs.com/api/drones/?format=json&limit=1/
LinkFormatter.droneDynamicsUrl = http://dronesim.facets-labs.com/api/{id}/dynamics/?format=json&limit=10&offset=%d
LinkFormatter.defaultsUrl = http://dronesim.facets-labs.com/api/dronedynamics/?format=json&limit=10&offset=%d

drones.url = http://dronesim.facets-labs.com/api/drones/?format=json&limit=5
droneTypes.url = http://dronesim.facets-labs.com/api/dronetypes/?format=json&limit=5